### ISSUE TITLE
Refactor AdjudicatorSubscription

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#118]
**Location**: `[backend/eth/*]` `AdjudicatorSubscription`  

**Problems**:  
1. The `AdjudicatorSubscription` tries to only return the latest event which can produce a race condition where the `Next` function and the event-replacement logic race.
2. The `Next() *Event` function of the `AdjudicatorSubscription` has a semantic that does not fit well with our usual subscription pattern.  
It just returns `nil` instead of waiting for a new event. In some cases this would mean that we have to use poll-loops to get all new events.  

**Possible solutions**:  
1. Since it is not possible to only return the last event in a non race-condition inducing way, i would do it as follows:
  - Return the last *past* event
  - Return all *future* events
2. Modify the `AdjudicatorSubscription` to look more like our generic event subscription.  
Concrete: Rename `Next` to `Read` and change its signature to `Read(ctx, sink chan *Event) error`.

**Comment by matthiasgeihs** [comment]
Regarding 2. It should return `nil` unless the subscription is closed. So this sounds like a bug.

**Comment by matthiasgeihs** [comment]
@ggwpez is this issue still relevant? if not, please close.

**Comment by ggwpez** [comment]
Well, i still dont like the code, but it is not relevant right now.
