### ISSUE TITLE
Option to register new asset ERC20 contracts after the channel client is initialized

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#121]
In the current implementation (c7113e1),

- The asset contracts address are set in the funder and the funder is passed onto the `client.New` when initializing the client.
- No asset contracts can be registered with the `funder` after the client is initialized.

But, given the large number of ERC20 contracts, it would be more convenient and easy to use if the ERC20 contracts can be registered with the funder after the client is initialized.

**Implementation hints**: 

A `RegisterAsset` method can be added to the `Funder` which updates the `accounts` and `depositors` maps in the `Funder`. In order to make the `Funder` thread-safe, a mutex could be added and `Fund`, `RegisterAsset` calls could use the mutex.

I also notice that, funder has a [`WithDepositor`](https://github.com/hyperledger-labs/go-perun/blob/c50c75f8aaf0ffb1002a13e44aa69971ce683e0b/backend/ethereum/channel/funder.go#L86) creates a copy of the funder and registers the asset in the copy. If creating a copy is a needed feature, then `RegisterAsset` can be added as a new method. If not, `RegisterAsset` could replace `WithDepositor`.

**Comment by matthiasgeihs** [comment]
In general, I don't see any argument against. However, we should make sure to test that properly, so that adding a depositor at runtime does not conflict with any framework functionality. This may be a bit tricky.

**Comment by manoranjith** [comment]
Yes, I agree that the implementation should ensure the functionality to be added should not conflict with the framework functionality. More specifically, calling the to-be implemented `RegisterAsset` method should not interfere with the existing `Fund` call.

Here is the concept I came up with considering the above points:

1. Add a method `CopyWithAssets(assets ...wallet.Address)` to the `Funder` that creates a deep copy of the funder with only only the mentioned asset details copied to the new funder.

2. In [`fundLedgerChannel`](https://github.com/hyperledger-labs/go-perun/blob/c7113e11ce8b8287bb6e8d05dbc75d2d5b485832/client/proposal.go#L527) part of the `ProposeChannel` API, instead of using the `client.funder` directly, a copy of this funder (using `CopyWithAssets` function) should be used for each channel. This copy should be created when starting the `ProposeChannel` call and not in the middle of the protocol. 

3. Add `RegisterAsset(asset Asset, d Depositor, acc accounts.Account)` and `IsRegistered(asset Asset)` methods on the `Funder`. Use a mutex on the 4 public APIs of the funder implementation to make them thread-safe. Because `RegisterAsset`, `IsRegistered` will be invoked by user of the framework while framework will invoke `CopyWithAssets`.

4.  Then, the funder could be used this way:

      a. User (for example say the `perun-node`) of the framework will maintain a copy of the parent `Funder`. 

      b. Before making `ProposeChannel` call, the user will check if all the assets required for the channel are registered in the (parent) funder. If not, user will register them before invoking `ProposeChannel`.

      The `RegisterAsset` or `IsRegistered` will be invoked on parent funder and framework will invoke `CopyWithAssets` on the parent funder before starting the channel proposal. During the channel proposal protocol, `Fund` will be invoked on the derived child funder and hence it will not be blocked by any other calls.

**Comment by manoranjith** [comment]
Your thoughts on this @matthiasgeihs

**Comment by matthiasgeihs** [comment]
As a side node: I am a bit confused at which places we talk about the funder interface and at which we talk about the Eth funder implementation.

Regarding 1. + 2.
I don't like the idea of adding CopyWithAssets and then using it to create a copy each time before calling the Fund method. It seems to make the usage of a funder a lot less intuitive.
I think it would be sufficient to document on the funder interface that the implementation should be thread-safe, i.e., `RegisterAsset` and `Fund` must not run concurrently.

Regarding 3.
Did you consider having `IsRegistered` return the associated depositor and account? I think this would be useful.

Do you propose to add the additional methods to the funder interface or the Eth implementation? We could start by adding them to the Eth implementation first, which would be sufficient for covering your use case, right?

**Comment by manoranjith** [comment]
Throughout, the discussion I am referring to funder implementation for ethereum.

On using a copy of the funder for each channel, I agree it is less intuitive. But,
1. The modification will be done in the `go-perun`'s implementation of `ProposeChannel` call as stated in point 2.

The reason is that,
1. Though `IsRegistered`, `RegisterAssert` and `Fund` calls are made thread-safe, it is very difficult for the user to guarantee that `RegisterAsset` and `Fund` does not run concurrently. For example, 

a. On `ch-1`, the node has called `ProposeChannel` and `funder.Fund` will be eventually invoked by go-perun after agreeing on the initial state of the channel.

b. At the same time, node could be processing a request for proposing another channel `ch-2`, where it finds an asset is not registered and invokes `RegisterAsset`. Though this call would finish very quickly, it may cause the `Fund` method to wait for the mutex for a very short duration of time.

Again, this is only an edge case, so we could also leave this for now (thereby drop the idea of using a copy of funder for each channel) and come back to it later.

**Comment by manoranjith** [comment]
Reg 3, in the proposed design, I considered only a boolean return value for `IsRegistered`. As you suggested, it would be good to return the depositor and the asset. I will update it now.

**Comment by matthiasgeihs** [comment]
Let's go for the simpler interface first. We can optimize later if there is need.

**Comment by manoranjith** [comment]
Okay, then I will do the first implementation which uses the same funder for all channels.

**Comment by matthiasgeihs** [comment]
Closed in #124
