### ISSUE TITLE
UpdateBy does not return an error when a channel update is rejected by the peer

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#125]
Error introduced in aa252f6b2c6a260dc225ab7d658774bf889961a1

UpdateBy function is expected to return a `PeerRejectedError` when a channel is rejected by the peer. This was working as expected until version 8066e90363e1c37345c51156726d2e3ee9529cfd and stopped working in aa252f6b2c6a260dc225ab7d658774bf889961a1.

On having a closer look, the cause of this bug is use of a [`defer statement in updateGeneric`](https://github.com/hyperledger-labs/go-perun/blob/afc727efdec2a534f57d66f62c56b6ec50d485ce/client/update.go#L175) function.

The defer statements checks if any error has occurred. If yes, then `discardUpdate` is invoked and error of the `discardUpdate` call replaces the actual error.

Possible solution:

Error from `discardUpdate` can be ignored, because [a comment ](https://github.com/hyperledger-labs/go-perun/blob/afc727efdec2a534f57d66f62c56b6ec50d485ce/client/update.go#L226)in `discardUpdate` function says it should never error.

**Comment by ggwpez** [comment]
The title states "[…] when a *channel* is rejected […]". Did you mean *update* instead here?  

`DiscardUpdate` can only error if there is no update to be discarded.  
So either:
1. Revert the hunk to how it was before
2. Change `DiscardUpdate` to return nothing  

We could add a test to prevent further regression but that would probably be a lot of effort.

**Comment by manoranjith** [comment]
The particular hunk aa252f6b2c6a260dc225ab7d658774bf889961a1 contain many other changes. So I feel, the concerned part alone can be fixed.

Can i then proceed with option 2 (change `DiscardUpdate` to return nothing or should I just leave `DiscardUpdate` as such and simply ignore the error from it in [this location](https://github.com/hyperledger-labs/go-perun/blob/afc727efdec2a534f57d66f62c56b6ec50d485ce/client/update.go#L175) ?
@ggwpez

**Comment by matthiasgeihs** [comment]
Nice catch. I made a bug fix proposal in #126 .

**Comment by matthiasgeihs** [comment]
Closed in #126
