### ISSUE TITLE
[wire/test] LocalBus for En/Decode testing

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#130]
**Location**: `[wire/test] localbus.go`, all test files that use `wire.NewLocalBus()`

**Problem**: Faulty En/Decode methods are not detected in tests which use the `wire.LocalBus`.  
The `LocalBus` just passes the objects in memory instead of En/Decoding them, which would be nice for testing.    

**Possible solution**: Add a `wire/test.LocalBus` (name up for debate :laughing:) which En-and Decodes the message objects instead of passing them through.

**Comment by matthiasgeihs** [comment]
Done in 7b2307f3
