### ISSUE TITLE
Virtual Channels Persistence Leak

### ISSUE THREAD

**Issue by sebastianst** [hyperledger-labs/go-perun#131]
Currently, VCs are not deleted on the hub's side after they got closed and the parent channels successfully updated.

This means that a hub's persistence would overflow with closed virtual channels.

Reference discussion:
> Not sure, but don't we also want to remove the virtual channel from persistence now? Or maybe I'm missing that this is happening somewhere else already...

_Originally posted by @sebastianst in https://github.com/hyperledger-labs/go-perun/pull/123#discussion_r661677055_

**Comment by matthiasgeihs** [comment]
The version with the persistence leaked will probably not be merged. I updated the corresponding MR #123 with a fix.

**Comment by matthiasgeihs** [comment]
Closing because not applicable anymore.
