### ISSUE TITLE
Update to geth >=1.10.6

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#149]
Try to update to geth >= 1.10.4 with a local overwrite of miguelmotas hd-wallet until https://github.com/miguelmota/go-ethereum-hdwallet/pull/16 is merged.  
 
Update: The geth changelog states that all geth users should update to >= 1.10.6 before Aug. 4th to remain consensual.

**Comment by matthiasgeihs** [comment]
I suggest we create a fork until it is merged and then reference the fork.

**Comment by ggwpez** [comment]
> I suggest we create a fork until it is merged and then reference the fork.

Yes i will consider it.
