### ISSUE TITLE
Current state in ChannelUpdate

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#15]
**Location**&emsp; `[client]`  

**Changes**&emsp; Add field `CurrentState` to `client.ChannelUpdate` to make the current state of a channel accessible.  
For version 1 updates it could either be the same as `State` or `null`.

**Context**&emsp; `channel.State()` can not be called in an ongoing `HandleUpdate` call.  
This makes it harder to use, since the user has to track the current state themself. Imagine:  
```go
func (c *Client) HandleUpdate(update client.ChannelUpdate, _ *client.UpdateResponder) {
    channel := c.getChannel(update.State.ID)
    current := channel.State()   // NOT POSSIBLE
}
```
It is not possible since the mutex of the machine that is associated with the channel is already locked.

**Acceptance criteria**&emsp; The state of a channel is accessible inside of an ongoing update in a threadsafe way.

**Comment by matthiasgeihs** [comment]
I think the acceptance criteria is currently wrong. It reads like one must be able to call `channel.State()` during update handling. I don't think this is what you want. For acceptance of a change, it is sufficient that one can read the channel state during update handling _in some way_, for example, through the ChannelUpdate object as you suggested.

**Related Observation:** When using this handler, I was surprised that it doesn't give a pointer to the channel object. I suggest that we also make the channel object available to the handler, for example, by adding it as a parameter.

**Comment by ggwpez** [comment]
>For acceptance of a change, it is sufficient that one can read the channel state during update handling _in some way_

Yes, i changed it.

>I suggest that we also make the channel object available to the handler, for example, by adding it as a parameter.

We could do that, but its mutex is locked so it would not be possible to call all functions on it.  
This maybe counter-intuitive and would need to be documented.

**Comment by ggwpez** [comment]
Since we use the `ChannelUpdate` struct at many other occasions it seemed easier to put the current state as argument into `HandleUpdate`.
