### ISSUE TITLE
Adjudicator.Subscribe takes `channel.Params` while only `channel.ID` is needed

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#173]
#### Situation: 
[`Adjudicator.Subscribe`](https://github.com/hyperledger-labs/go-perun/blob/06c5c9577b85ee0e3b7147cd19ff68ec54e5e569/channel/adjudicator.go#L63) API  currently takes `channel.Params` as an argument. However, looking at the implementation of [`Subscribe`](https://github.com/hyperledger-labs/go-perun/blob/06c5c9577b85ee0e3b7147cd19ff68ec54e5e569/backend/ethereum/channel/subscription.go#L36) for ethereum, I noticed only the `ID` field in `params` is used. 

#### Problem

I noticed this when implementing the watcher for IoT use cases (#172). In the design of Watcher described in proposal#004, the client should register the channel by sending the `channel.ID`. Watcher would then subscribe for adjudicator events for this channel using this channel ID.

Because, the `Subscribe` API requires `channel.Params`, it will be required to pass `channel.Params` all over, while it needs only `channel.ID`.

#### Possible solution

Modify the `Adjudicator.Subscribe` API to take `channel.ID` instead of `channel.Params`

**Comment by manoranjith** [comment]
@matthiasgeihs @ggwpez

**Comment by matthiasgeihs** [comment]
I made the same observation before. However, is there really a need to change this? I understand that having to pass around additional data seems inconvenient, but not like a major problem.

Changing backend interfaces affects all backend implementations and should only be done if justified clearly.

**Comment by manoranjith** [comment]
`Can we do without this change....?`

Yes, technically, it would be possible the `Watcher` without applying this change. In that case, the `StartWatching` function will take `channel.Params` instead of just `channel.State`.

But, this means because of `Adjudicator.Subscribe` function needing more than required arguments, other components using it (`StartWatching` API in this case) will also take additional arguments.

`Justification...`

Looking at the implementation of `Adjudicator.Subscribe` and its usage, it appeared that `channel.State` was sufficient. Not fixing this now means, effects will creep into `StartWatching` and later we would have to think more about fixing this as it involves more APIs.

@matthiasgeihs

**Comment by matthiasgeihs** [comment]
During a discussion with @ggwpez the idea came up that we might want to take a grooming break at a suitable point in time where we address a bunch of such "cosmetic" issues together. I fear that if we do such interface changes on the fly while we concurrently on other parts of go-perun, we risk losing a lot more time than if we do them together in one go.

That being said, you are making a strong argument, that the change you propose should not be postponed.

> Not fixing this now means, effects will creep into StartWatching

In this case, I am fine with changing it now.

**Comment by manoranjith** [comment]
Yeah, I agree that in most cases, we should collect such tasks in an issue and take it periodically.

I also noticed @ggwpez has created an issue for the same.
