### ISSUE TITLE
Travis CI is no longer supported

### ISSUE THREAD

**Issue by ryjones** [hyperledger-labs/go-perun#2]
Travis CI has changed how open source projects are supported, and Hyperledger can no longer build there. I suggest GitHub Actions as a replacement.

**Comment by ggwpez** [comment]
Yes thanks, will be fixed soon.

**Comment by sebastianst** [comment]
What about Github Actions? cc @ggwpez @matthiasgeihs

**Comment by ryjones** [comment]
GitHub actions is the way to go
