### ISSUE TITLE
Error handling: Blockchain node not reachable

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#21]
In the current implementation of `ethereum` blockchain backend, the user (of the framework) is expected to initialize a connection to the blockchain node and pass it to the [`NewContractBackend`](https://github.com/hyperledger-labs/go-perun/blob/40386090ed391658f68ca6a8e1f70ff8b93a4ae7/backend/ethereum/channel/contractbackend.go#L59) function in channel package.

If the connection to blockchain node is lost after a [`ContractBackend`](https://github.com/hyperledger-labs/go-perun/blob/40386090ed391658f68ca6a8e1f70ff8b93a4ae7/backend/ethereum/channel/contractbackend.go#L53) is created, then it is detected only when one of the method calls (invoked at later point of time) that interact with the blockchain node fails. The resulting error message is directly returned to the user.

I think, in this scenario, the user should be 
1. Receiving a named error (say `ChainNotReachableError`).
2. Able to restart the protocol from the intermediate state of where it stopped after fixing the connection)

The second point described above is also related to #20. 
For the first point, one suggestion is that we can add the named error to the core of the SDK and update the functions in the backend implementations to return this error in appropriate scenarios. As far as see, this error is not returned as a named error by the `ethclient` library. So there could be multiple approaches on how we want to detect this error in the ethereum backend.

**Comment by manoranjith** [comment]
Concept for detecting and reporting this error:

On inspecting the error string, I see that we can check the phrase `connection refused` in the error message. If it is present then, it can be treated as `ChainNotReachableError`). This is kind of hacky, but i think since the implementation will be local to [backend/ethereum] package, it will work well.
 
We can add this check after each call that interacts with the chain in the [backend/ethereum] package.

Request for you comments on this @ggwpez @matthiasgeihs .

**Comment by ggwpez** [comment]
Just searching for the `connection refused` string would probably catch most cases, but i dont know if it is platform independent.  
Golang translates the posix error `ECONNREFUSED` into `connection refused` but what happens on Windows? We should test that at least once.  
There can also be other reasons for the connection to fail, which results in different error messages being returned (eg. `websocket: close 1006 (abnormal closure): unexpected EOF`). So maybe change the name of the error into something more concrete, for example `ChainConnectionRefused`.

**Comment by manoranjith** [comment]
That's a good point regarding possibility of other errors phrases. So renaming the error might fix this.

On the other hand, I am not sure if we need to be concerned for the errors in case of windows. Is the current version targeting this (support for other OS platforms) in any other parts of the project ?
