### ISSUE TITLE
`TestAdjudicator_ConcludeFinal` occasionally fails in the CI Pipeline when running tests with the `--race` flag.  

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#217]
### Problem
`TestAdjudicator_ConcludeFinal` occasionally fails in the CI Pipeline when running tests with the `--race` flag. The test passes when the job is re-run.

For instance, it [passes](https://github.com/hyperledger-labs/go-perun/runs/3651916852?check_suite_focus=true) here and fails [here](https://github.com/hyperledger-labs/go-perun/pull/214/checks?check_run_id=3651947200).

**Comment by matthiasgeihs** [comment]
Closed until the failure reoccurs.
