### ISSUE TITLE
Make Asset comparable

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#247]
I think we should extend the `Asset` interface (not in this MR).  
`EqualEncoding` was a work-around from the beginning.

_Originally posted by @ggwpez in https://github.com/hyperledger-labs/go-perun/pull/240#discussion_r737525058_

**Comment by ggwpez** [comment]
So how about an `Equals(Asset, Asset)` method? We do not seem to need ordering, so `Cmp` would be overkill.
