### ISSUE TITLE
Move [log] to poly-go

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#263]
### Location
Package `[log]` and `[log/logrus]`.

### Problem
Project agnostic code in _go-perun_.

### Proposal
Package `log` seems to be quite independent of _go-perun_ and could therefore be moved to _poly-go_

**Comment by matthiasgeihs** [comment]
The log package is specific to go-perun as it represents the logging abstraction. I don't think it is useful to move it to the poly-go repo. Closing this issue for now as I am currently trying to clean up the list of open issues.
