### ISSUE TITLE
Use `main` instead of `dev` branch

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#265]
### Location
git

### Problem
We use `dev` branch for development. And `main` branch we only update after a release. I currently don't see a clear benefit in separating the two. (Maybe @sebastianst can comment.) On the downside, it requires additional work to maintain two branches. Updating `main` is a manual task which we tend to forget (like this time again) and which requires us disabling branch protection for a short time period (if I see correctly). The main point is that having the two branches adds complexity while I don't really see a benefit at the moment.

### Proposal
We use `main` for development. We delete `dev`.

@sebastianst @ggwpez

**Comment by sebastianst** [comment]
I agree, let's just use a single `main` branch. The reason for using a separate `dev` branch was simply that we started out with the [git flow](https://nvie.com/posts/a-successful-git-branching-model/) branching model. But I agree that it is overkill at this point in time.
