### ISSUE TITLE
Linter does not report undocumented publics

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#267]
### Location
`.golangci.yml`

### Problem
The [default suppression](https://golangci-lint.run/usage/configuration/) filter of golangci-lint removes the "should have comment or be unexported" warnings.  
Therefore public types/functions without comment currently pass the CI unnoticed.  

### Proposal
This can be disabled with `exclude-use-default: false` but would then require us to copy the remaining defaults that we still want to use.  
Just copying some of the default values does not seem to work so well either, since some are deprecated…

**Comment by matthiasgeihs** [comment]
Oh, I thought this was enabled again by now. What's your suggestion? How should we deal with this?
