### ISSUE TITLE
Handle channel update: Channel may not be locked during update response

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#270]
### Location
client/update.go

### Problem
When a client receives an update proposal via `handleUpdateReq`, it forwards a responder object to the user for reacting to the update. The code implicitly assumes that `responder.Accept` will be triggered on the same thread. If not, `handleUpdateReq` will return and the channel will be unlocked. If `responder.Accept` is triggered later, the channel state will be changed without acquiring the mutex.

### Proposal
Make sure that the channel lock is acquired during `handleUpdateAcc`, even if the response via `responder.Accept` happens after `handleUpdateReq` has returned. I believe we should await the response asynchronously.

https://github.com/hyperledger-labs/go-perun/blob/bab7652c5c41731290fcb837452e40d03942e44f/client/update.go#L315
```go
go uh.HandleUpdate(c.machine.State().Clone(), req.Base().ChannelUpdate, responder)
```
(We should also clone the machine state before passing it to the user.)

**Comment by ggwpez** [comment]
I thought this was documented, but somehow not? Calling if from other threads is indeed undefined.  

Would your proposal not allow to reorder the execution of updates?  
I would rather wait *synchronously* for the update responder to finish and then return the `handleUpdateReq` func. Eg:
```go
uh.HandleUpdate(c.machine.State().Clone(), req.Base().ChannelUpdate, responder)

if accepted := responder.waitForUser(); accepted {
    // Execute the update.
} else {
    // Reject the update.
}
```
Could be simplified even more to let the `HandleUpdate` return a bool.  
@matthiasgeihs

**Comment by matthiasgeihs** [comment]
We would need to find a way to deal with these cases. For example, we could let one update overwrite another. The state machine should be kept in a state where it is clear that in update is in progress. And we should be able to resume the update when the response comes in.
