### ISSUE TITLE
Settle channel when funding fails

### ISSUE THREAD

**Issue by cryptphil** [hyperledger-labs/go-perun#344]
### Location
https://github.com/hyperledger-labs/go-perun/blob/1e496bd3ce7cfd3712b7d3fdff5e74616bf52bba/client/proposal.go#L185

### Problem
If funding a channel fails, we currently only return the funding error but any funds that may already have been deposited to the `AssetHolder` aren't automatically returned.

### Proposal
If the funding fails, the client should directly settle the channel in order to withdraw funds that may have been deposited.

**Comment by matthiasgeihs** [comment]
Closed by #349
