### ISSUE TITLE
Replace `context.TODO()` with appropriate context

### ISSUE THREAD

**Issue by cryptphil** [hyperledger-labs/go-perun#357]
### Location
https://github.com/hyperledger-labs/go-perun/blob/e831f7ec3d1fee283cc66a3035969a2c7b9aad71/watcher/local/watcher.go#L311

### Problem
We use a `context.TODO()` which should not be contained in the release version of the codebase imo.

### Proposal
Replace it with an appropriate context, e.g., background or give `handleEventsFromChain` a context.

**Comment by matthiasgeihs** [comment]
Done in #360
