### ISSUE TITLE
Recover funds after funding transaction timeout (Ethereum)

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#42]
**Problem**
As mentioned in #20, a channel opening can fail while channel funding is in progress (e.g., if the funding confirmation is not  received within the specified waiting period). There is currently no convenient method to withdraw the funds in that case.

**Solution**
1. Persist the channel before submitting the funding transaction.
2. If the channel opening fails, wait until the funding transaction is confirmed and initiate channel settling afterwards.

**Comment by manoranjith** [comment]
@matthiasgeihs  Currently a `fundingTimeout` that is same as `Challenge Duration`(see [here](https://github.com/hyperledger-labs/go-perun/blob/0fe85e73b5684c2c55727559c00c5ef44cfaa0a1/backend/ethereum/channel/funder.go#L81)).

When this timeout expires, the `loop that waits for Funding events` within the `Funder` will abort. If we try to initiate channel settling after this, should we increase the timeout value to accommodate for  genuine delays in the transaction getting mined ?

**Comment by manoranjith** [comment]
Or do you think, the `Challenge Duration` will be sufficient to accommodate for those delays ?

**Comment by matthiasgeihs** [comment]
Related to #239

**Comment by matthiasgeihs** [comment]
Closed in #349
