### ISSUE TITLE
Issues with usage of abigen and solc in `generate.sh`

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#47]
Related to https://github.com/hyperledger-labs/go-perun/discussions/46#discussioncomment-605230

Our `generate.sh` script has the following issues:

1. We run `solc` twice (once with abigen for the bindings, once for the binary runtime), potentially creating inconsistencies.
2. `solc` with abigen does not allow configuration parameters.

**Comment by ggwpez** [comment]
Closed by #48.
