### ISSUE TITLE
Error level logs should be printed by default

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#64]
It seems like if no logger is set up, runtime errors happening in the backend are not visible. This is problematic because relevant information might be hidden from a user. For example, when the funder fails to perform a channel funding operation, the user will just see "did not fund channel in time", while the logger actually has some more information "out of gas" or "failed to increase allowance".

I suggest that we make such error level logs visible to the user by default, for example, by printing them to stdout if no logger is set.

**Comment by ggwpez** [comment]
I like the idea. I set the default log level in the `client` package to `warn` now.  
After testing it with the tutorial app, this seems to print funding errors. Maybe you can also test it?  
Code is in #66
