### ISSUE TITLE
[client] NewFundingTimeoutErrror can return error as value instead of pointer.

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#73]
Currently, `NewFundingTimeoutErrror`, the constructor for error type `FundingTimeoutError` [returns a pointer](https://github.com/hyperledger-labs/go-perun/blob/bf29b2bf504f57261e04601e31e3a3cf9cafee43/channel/funder.go#L76) instead of value. This makes the usage of the error type tricky.

For example, the [`client.Proposal`](https://github.com/hyperledger-labs/go-perun/blob/bf29b2bf504f57261e04601e31e3a3cf9cafee43/client/proposal.go#L145) returns `PeerRejectedError`, `RequestTimedoutError`, `FundingTimedoutError` and few more.

Since each of the other errors are generated as values by their respective constructors, then can be retrieved as below:
```
peerRejectedError := pclient.PeerRejectedError{}
ok := errors.As(err, &peerRejectedError)
```

But for `FundingTimeoutError`, a double pointer should be used
```
fundingTimeoutError := &pchannel.FundingTimeoutError{}
ok := errors.As(err, &fundingTimeoutError)
```

Is there a specific reason for returning a pointer in this case ?

If not, I think constructor of `FundingTimeoutError` can be updated to return a value, so that it is more idiomatic and does not requires an exception when handling the error.

**Comment by ggwpez** [comment]
It was designed to work together with the inbuilt function `IsFundingTimeoutError` but i dont know why specifically a pointer instead of an instance was used.  
If you want to update it you can do, looks like 2-3 test cases need a small change.
