### ISSUE TITLE
Indicate proposer index in channel proposal

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#79]
Currently, in a channel proposal, we have the convention that the proposer has index 0. However, this is not documented well and not evident. Furthermore, the framework does not give an indication of that fact via, for example, a property on the proposal object (e.g., `proposal.ProposerIndex`) or the client package (e.g., `client.ProposerIndex`).

I think implicit assumptions like that are bad style. For example, if we, for whatever reason, decide to change away from this assumption, it will be difficult to make the framework user aware of that change. If we, at least, indicate this assumption via a property on some object, transitioning to a different behavior will be easier.

**Comment by ggwpez** [comment]
Adding something like `client.ProposerIndex` seems reasonable to me.  
This could then also be used when creating the initial balance allocation or accessing a channel state.

**Comment by sebastianst** [comment]
Yes, we followed this convention for simplicity and because in ledger channels it didn't seem like a limitation.

Exposing a `const client.ProposerIndex` constant sounds good.

It wouldn't be Go style to expose it as a static value on a struct, a package-wide constant would be better.
