### ISSUE TITLE
Calling settle with secondary option for the non collaborative close

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#8]
#### Description

This is regarding the closure of channel in non collaborative manner as described below. Lets assume `Alice` initiates closure of a channel with bob. The channel state is not marked final.

1. `Alice`: calls `register`.
2. `Alice` and `Bob` received RegisteredEvent.
3. Now there are few possibilities:
    a. Both `Alice` and `Bob` do not want to conclude the channel, they continue to do off-chain transactions. This however will eventually lead to case `b` or `c`.
    b. `Bob` expects `Alice` to call `conclude`, so `Bob` ignores the event and waits; `Alice` calls `conclude` within expected duration.
    c. Same as `b`, but `Alice` doesn't call conclude within the expected time period, so `Bob` calls `conclude`. Unfortunately it was exactly during the same time that `Alice` also calls `conclude`.
    
4. Case `b` is not a problem. But in case `c`, the `conclude` call that is processed second by the blockchain will fail and the channel will already have been concluded. This case also is not covered by `secondary` logic is applied only when the state of the channel is final (i understand it this way by looking [here](https://github.com/hyperledger-labs/go-perun/blob/37f6187c1df8d05409853c4eb7301a384f12923b/backend/ethereum/channel/conclude.go#L59)).

This issue also relates to #7 created by @ggwpez. I think one of the solution could be to create a provision to wait for N blocks (first by adding/updating an interface in the core of the framework, then by adding the corresponding implementation in the ethereum backend). This could also remove the need for secondary logic, which now is propagated across many functions/methods in the `go-perun` framework. 

#### Steps to reproduce:

To reproduce this issue:
1. Clone [this version](https://github.com/hyperledger-labs/perun-node/pull/161/commits/d30e43ad157c3b63bb28d26fc247816633319c42) of `perun-node`.
2. Comment out lines `172-174` in `session/channel.go`
3. Start ganache-cli node using the below command (in a separate terminal):
```
ganache-cli -b 1 --account="0x1fedd636dbc7e8d41a0622a2040b86fea8842cef9d4aa4c582aad00465b7acff,100000000000000000000" --account="0xb0309c60b4622d3071fad3e16c2ce4d0b1e7758316c187754f4dd0cfb44ceb33,100000000000000000000"
```
4. Run `Test_Integ_Role` with the below command:
```
cd session
cd session && go test -cover -p 1 -count=1 -tags=integration -run Test_Integ_Role
```

5. The following phrase can be found in the tests logs. By looking at the failed transaction ID in the ganache-cli logs and the transaction IDs in the test log, the transaction can be found corresponding to `conclude` call.

**Comment by ggwpez** [comment]
As far as i understood the issue, i dont see the incentive for *Alice*.  

Propose *Alice* opens a dispute by calling `Register` with a *non-final* state.  
Why would *Alice* not want to call *Conclude* afterwards? Does she not want to unlock her funds?  
The only thing here is that a malicious *Alice* could force *Bob* to waste gas by sending a `Conclude` tx immediately as he does. But this is also possible for `Register`.  

Regarding `4.`: You are correct, a dispute bypasses the `secondary` logic since the user normally wants the tx to be sent immediately to not miss a timeout.  
I will write something in the other issue about the `waitNBlocks` function.

**Comment by manoranjith** [comment]
Regarding 4, I think in case of disputes `register`  will be automatically called by the `Watcher` go-routine. The user of `go-perun` would call `register` when these is no challenge. 

This is my understanding, but I am not sure if this is the way it actually is. @ggwpez

**Comment by matthiasgeihs** [comment]
As mentioned in #7 , I don't see a problem in colliding transactions. Concretely, if the channel has been concluded already, and the second conclude call fails, there is no problem with that, as the result is the intended one. Just log the error, and continue with execution as normal.

**Comment by matthiasgeihs** [comment]
We may consider this optimization at a later point when it becomes relevant in a concrete use case. Closing this issue for now.
