### ISSUE TITLE
Virtual channels

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#82]
There are at least three different types of channels that we consider in go-perun:

- A **ledger channel** is a channel that it is funded on-chain. It can be established between any participants in the network.
- A **sub-channel** is a channel that is funded off-chain from a parent channel. Its participants are the same as in the parent channel.
- A **virtual channel** is a channel that is funded off-chain from a set of parent channels. It can be established between participants that have a channel to a common intermediary.

Currently, go-perun supports ledger channels and sub-channels. The goal of this issue is to enable virtual channels in go-perun. Virtual channels are essential for establishing a channel network.

**Comment by matthiasgeihs** [comment]
## Plan

### Modify contracts
* Add field `uint16[] indexMap` to struct `SubAlloc`. This field describes how participant indices from the current channel are remapped to participant indices in the referenced sub-channel.
* Change `register` to allow and enforce registration of a channel with all sub-channels.
* Change `pushOutcome` to account for participant index remapping. Also ensure that sub-channel outcome does not exceed the allocated amount.

### Modify core
* Update contract bindings
* Add field `participantIndexMap []Index` to type `SubAlloc`.
* Change register to register with sub-channels.
* Implement virtual channel functionality (channel opening, channel settlement)

**Comment by sebastianst** [comment]
Don't we also need to hash the new `bool ledgerChannel` into the channel id calculation? Otherwise, users can just set it like they want.
