### ISSUE TITLE
Merge EventSub.{ReadAll|ReadPast|ReadFuture} into Read

### ISSUE THREAD

**Issue by ggwpez** [hyperledger-labs/go-perun#93]
**Location**: `[backend/ethc/channel/subscription]`

**Task**: Instead of having three different read functions: `ReadAll`, `ReadPast` and `ReadFuture` we only want to have a single `Read` function.  
This simplifies the event sub code a lot and the cases that the other functions cover are not needed right now.

**Comment by ggwpez** [comment]
The idea of removing `ReadPast` works in theory, but after doing so all of our Funder and Adjudicator tests needed to be adjusted.  
The tests also needed 33 instead of the current 6 seconds. I think it is therefore better to just remove `ReadFuture` and rename `ReadAll` to `Read` for now.  

We only need the `ReadPast` function in one location that we wanted to revise anyway so fixing all tests is not worth the effort IMHO.  
@matthiasgeihs

**Comment by matthiasgeihs** [comment]
OK, thanks for looking into it. I am fine with taking your suggested approach (i.e., keep `ReadPast` for now). In the long term, I think we should still consider replacing `ReadPast` with `Read`.
